defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

train_factors: [1, 3]
test_factors: [5]
beta: 2
noise: 0.
num_train_envs: 2
noise_dims: 1

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10

device: cpu

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false

seed: 1

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./${env}/${agent.name}_${experiment}
